# Generated by Django 5.1 on 2024-09-18 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Noname', max_length=255)),
                ('brand', models.CharField(default='Unknown', max_length=255)),
                ('desc', models.TextField(default=None)),
                ('price', models.BigIntegerField(default=0)),
                ('title', models.CharField(default='Notitle', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_img/')),
            ],
        ),
        migrations.CreateModel(
            name='UserCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BigIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
        ),
    ]
