# Generated by Django 5.1 on 2024-09-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_title_alter_item_desc_alter_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
