# Generated by Django 5.1 on 2024-09-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercartitem',
            name='quantity',
            field=models.BigIntegerField(default=0),
        ),
    ]
