# Generated by Django 5.1 on 2024-09-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_usercartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='filename',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
    ]
