# Generated by Django 5.1 on 2024-09-17 21:18

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_remove_item_filename_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pathlib.PurePosixPath('/home/ecs-user/application/scripts/vueProject/public/item_img')),
        ),
    ]
