# Generated by Django 5.1 on 2024-08-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tel',
            field=models.CharField(default='00000000000', max_length=11),
        ),
        migrations.AddField(
            model_name='customuser',
            name='uid',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
