# Generated by Django 5.1 on 2024-08-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tel',
            field=models.CharField(default='', max_length=11, unique=True),
        ),
    ]
