# Generated by Django 5.1 on 2024-09-17 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='South Korea', max_length=255)),
                ('city', models.CharField(default='Seoul', max_length=255)),
                ('street', models.TextField(blank=True, default='', max_length=2048, null=True)),
                ('room', models.CharField(blank=True, default='', max_length=255)),
                ('pcode', models.CharField(default='', max_length=255)),
                ('receiver', models.TextField(default='Unknown', max_length=2048)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.address'),
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
